<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MViG7rR' shared service.

return $this->privates['.service_locator.MViG7rR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'competenceRepository' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService.php', true],
], [
    'competenceRepository' => 'App\\Repository\\CompetenceRepository',
]);
