<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4DpmMtq' shared service.

return $this->privates['.service_locator.4DpmMtq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'competenceRepository' => ['privates', 'App\\Repository\\CompetenceRepository', 'getCompetenceRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
], [
    'competenceRepository' => 'App\\Repository\\CompetenceRepository',
    'paginator' => '?',
]);
