<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WC1EKhZ' shared service.

return $this->privates['.service_locator.WC1EKhZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contact' => ['privates', '.errored..service_locator.WC1EKhZ.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.WC1EKhZ": it references class "App\\Entity\\Contact" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'formationDossierDateManager' => ['privates', 'App\\Manager\\FormationDossierDateManager', 'getFormationDossierDateManagerService.php', true],
    'formationDossierDateRepository' => ['privates', 'App\\Repository\\FormationDossierDateRepository', 'getFormationDossierDateRepositoryService.php', true],
    'formationDossierRepository' => ['privates', 'App\\Repository\\FormationDossierRepository', 'getFormationDossierRepositoryService.php', true],
    'manager' => ['privates', 'App\\Manager\\ContactManager', 'getContactManagerService.php', true],
], [
    'contact' => 'App\\Entity\\Contact',
    'em' => '?',
    'formationDossierDateManager' => 'App\\Manager\\FormationDossierDateManager',
    'formationDossierDateRepository' => 'App\\Repository\\FormationDossierDateRepository',
    'formationDossierRepository' => 'App\\Repository\\FormationDossierRepository',
    'manager' => 'App\\Manager\\ContactManager',
]);
