<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qCozEGi' shared service.

return $this->privates['.service_locator.qCozEGi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'assomenuutilisateurRepository' => ['privates', 'App\\Repository\\AssomenuutilisateurRepository', 'getAssomenuutilisateurRepositoryService.php', true],
    'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
], [
    'assomenuutilisateurRepository' => 'App\\Repository\\AssomenuutilisateurRepository',
    'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
]);
