<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MeXGW.a' shared service.

return $this->privates['.service_locator.MeXGW.a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contactRepo' => ['privates', 'App\\Repository\\ContactRepository', 'getContactRepositoryService.php', true],
    'dossierRepo' => ['privates', 'App\\Repository\\FormationDossierRepository', 'getFormationDossierRepositoryService.php', true],
    'noteRepo' => ['privates', 'App\\Repository\\NoteRepository', 'getNoteRepositoryService.php', true],
], [
    'contactRepo' => 'App\\Repository\\ContactRepository',
    'dossierRepo' => 'App\\Repository\\FormationDossierRepository',
    'noteRepo' => 'App\\Repository\\NoteRepository',
]);
