<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\FormationDossierManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Manager/FormationDossierManager.php';

return $this->privates['App\\Manager\\FormationDossierManager'] = new \App\Manager\FormationDossierManager($this, ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
