<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.rAz3p6n.App\Entity\Propal' shared service.

include_once $this->targetDirs[3].'/src/Entity/Propal.php';

return $this->privates['.errored..service_locator.rAz3p6n.App\\Entity\\Propal'] = new \App\Entity\Propal();
