<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.B0eNFkg' shared service.

return $this->privates['.service_locator.B0eNFkg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'dossierManager' => ['privates', 'App\\Manager\\FormationDossierManager', 'getFormationDossierManagerService.php', true],
    'formationDossierRepository' => ['privates', 'App\\Repository\\FormationDossierRepository', 'getFormationDossierRepositoryService.php', true],
], [
    'dossierManager' => 'App\\Manager\\FormationDossierManager',
    'formationDossierRepository' => 'App\\Repository\\FormationDossierRepository',
]);
