<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wOluIyy' shared service.

return $this->privates['.service_locator.wOluIyy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adresseRepository' => ['privates', 'App\\Repository\\AdresseRepository', 'getAdresseRepositoryService.php', true],
    'civiliteRepository' => ['privates', 'App\\Repository\\CiviliteRepository', 'getCiviliteRepositoryService.php', true],
    'contactRepository' => ['privates', 'App\\Repository\\ContactRepository', 'getContactRepositoryService.php', true],
    'critFinOpcaRepository' => ['privates', 'App\\Repository\\CritFinOpcaRepository', 'getCritFinOpcaRepositoryService.php', true],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'manager' => ['privates', 'App\\Manager\\OpcaManager', 'getOpcaManagerService.php', true],
    'opcaNoteRepository' => ['privates', 'App\\Repository\\OpcaNoteRepository', 'getOpcaNoteRepositoryService.php', true],
    'secteurRepository' => ['privates', 'App\\Repository\\SecteurActiviteRepository', 'getSecteurActiviteRepositoryService.php', true],
    'urlRepository' => ['privates', 'App\\Repository\\UrlRepository', 'getUrlRepositoryService.php', true],
], [
    'adresseRepository' => 'App\\Repository\\AdresseRepository',
    'civiliteRepository' => 'App\\Repository\\CiviliteRepository',
    'contactRepository' => 'App\\Repository\\ContactRepository',
    'critFinOpcaRepository' => 'App\\Repository\\CritFinOpcaRepository',
    'em' => '?',
    'manager' => 'App\\Manager\\OpcaManager',
    'opcaNoteRepository' => 'App\\Repository\\OpcaNoteRepository',
    'secteurRepository' => 'App\\Repository\\SecteurActiviteRepository',
    'urlRepository' => 'App\\Repository\\UrlRepository',
]);
