<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rWMuJfT' shared service.

return $this->privates['.service_locator.rWMuJfT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['privates', 'App\\Manager\\ContactManager', 'getContactManagerService.php', true],
], [
    'manager' => 'App\\Manager\\ContactManager',
]);
