<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NzmAguk' shared service.

return $this->privates['.service_locator.NzmAguk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'factureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
], [
    'factureRepository' => 'App\\Repository\\FactureRepository',
    'paginator' => '?',
]);
