<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Fq.SH.o' shared service.

return $this->privates['.service_locator.Fq.SH.o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'formationDossierRepo' => ['privates', 'App\\Repository\\FormationDossierRepository', 'getFormationDossierRepositoryService.php', true],
], [
    'formationDossierRepo' => 'App\\Repository\\FormationDossierRepository',
]);
