<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.m7U3a1E' shared service.

return $this->privates['.service_locator.m7U3a1E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'encaissement' => ['privates', '.errored..service_locator.m7U3a1E.App\\Entity\\Encaissement', NULL, 'Cannot autowire service ".service_locator.m7U3a1E": it references class "App\\Entity\\Encaissement" but no such service exists.'],
    'encaissementRepository' => ['privates', 'App\\Repository\\EncaissementRepository', 'getEncaissementRepositoryService.php', true],
    'factureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService.php', true],
], [
    'em' => '?',
    'encaissement' => 'App\\Entity\\Encaissement',
    'encaissementRepository' => 'App\\Repository\\EncaissementRepository',
    'factureRepository' => 'App\\Repository\\FactureRepository',
]);
