<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YkyjJs6' shared service.

return $this->privates['.service_locator.YkyjJs6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService.php', true],
], [
    'villeRepository' => 'App\\Repository\\VilleRepository',
]);
