<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\ContactCustomType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/ContactCustomType.php';

return $this->privates['App\\Form\\ContactCustomType'] = new \App\Form\ContactCustomType(($this->privates['App\\Form\\DataTransformer\\CiviliteTransformer'] ?? $this->load('getCiviliteTransformerService.php')), ($this->privates['App\\Form\\DataTransformer\\QualiteTransformer'] ?? $this->load('getQualiteTransformerService.php')));
