<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\FormationDossierDateManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Manager/FormationDossierDateManager.php';

return $this->privates['App\\Manager\\FormationDossierDateManager'] = new \App\Manager\FormationDossierDateManager(($this->privates['App\\Repository\\FormationDossierRepository'] ?? $this->load('getFormationDossierRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
