<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\OpcaType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/OpcaType.php';

return $this->privates['App\\Form\\OpcaType'] = new \App\Form\OpcaType(($this->privates['App\\Repository\\ContactRepository'] ?? $this->load('getContactRepositoryService.php')), ($this->privates['App\\Form\\DataTransformer\\SecteurActiviteTransformer'] ?? $this->load('getSecteurActiviteTransformerService.php')), ($this->privates['App\\Form\\DataTransformer\\QualiteTransformer'] ?? $this->load('getQualiteTransformerService.php')), ($this->privates['App\\Form\\DataTransformer\\SiteWebTransformer'] ?? $this->load('getSiteWebTransformerService.php')));
