<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FactureDomiciliation extends \App\Entity\FactureDomiciliation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'idfacturedom', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'date', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'remise', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'tva', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'ht', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'ttc', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'dateestimepaiement', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'payeur', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'domiciliation', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'tvaTotal', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'structure', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'statutCommission', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'depotGarantie'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'idfacturedom', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'date', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'remise', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'tva', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'ht', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'ttc', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'dateestimepaiement', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'payeur', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'domiciliation', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'tvaTotal', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'structure', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'statutCommission', '' . "\0" . 'App\\Entity\\FactureDomiciliation' . "\0" . 'depotGarantie'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FactureDomiciliation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdfacturedom($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfacturedom', [$id]);

        return parent::setIdfacturedom($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfacturedom()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdfacturedom();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfacturedom', []);

        return parent::getIdfacturedom();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero(string $numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemise', []);

        return parent::getRemise();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemise(?float $remise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemise', [$remise]);

        return parent::setRemise($remise);
    }

    /**
     * {@inheritDoc}
     */
    public function getTva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTva', []);

        return parent::getTva();
    }

    /**
     * {@inheritDoc}
     */
    public function setTva(float $tva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTva', [$tva]);

        return parent::setTva($tva);
    }

    /**
     * {@inheritDoc}
     */
    public function getHt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHt', []);

        return parent::getHt();
    }

    /**
     * {@inheritDoc}
     */
    public function setHt(float $ht)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHt', [$ht]);

        return parent::setHt($ht);
    }

    /**
     * {@inheritDoc}
     */
    public function getTtc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTtc', []);

        return parent::getTtc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTtc(float $ttc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTtc', [$ttc]);

        return parent::setTtc($ttc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateestimepaiement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateestimepaiement', []);

        return parent::getDateestimepaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateestimepaiement($dateestimepaiement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateestimepaiement', [$dateestimepaiement]);

        return parent::setDateestimepaiement($dateestimepaiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeur(): ?\App\Entity\Payeur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeur', []);

        return parent::getPayeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeur(\App\Entity\Payeur $payeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeur', [$payeur]);

        return parent::setPayeur($payeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomiciliation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomiciliation', []);

        return parent::getDomiciliation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomiciliation(\App\Entity\Domiciliation $domiciliation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomiciliation', [$domiciliation]);

        return parent::setDomiciliation($domiciliation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTvaTotal(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTvaTotal', []);

        return parent::getTvaTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTvaTotal(float $tvaTotal = NULL): \App\Entity\FactureDomiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTvaTotal', [$tvaTotal]);

        return parent::setTvaTotal($tvaTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructure(): ?\App\Entity\Structure
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructure', []);

        return parent::getStructure();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructure(\App\Entity\Structure $structure = NULL): \App\Entity\FactureDomiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructure', [$structure]);

        return parent::setStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\App\Entity\FactDomNote $commentaire): \App\Entity\FactureDomiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', [$commentaire]);

        return parent::addCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\App\Entity\FactDomNote $commentaire): \App\Entity\FactureDomiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', [$commentaire]);

        return parent::removeCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutCommission(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutCommission', []);

        return parent::getStatutCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutCommission(?int $statutCommission): \App\Entity\FactureDomiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutCommission', [$statutCommission]);

        return parent::setStatutCommission($statutCommission);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotGarantie(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotGarantie', []);

        return parent::getDepotGarantie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotGarantie(?float $depotGarantie): \App\Entity\FactureDomiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotGarantie', [$depotGarantie]);

        return parent::setDepotGarantie($depotGarantie);
    }

}
