<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Domiciliation extends \App\Entity\Domiciliation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'ref', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'salle', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'signature', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'fixe', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'recu', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'tva', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'accord', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'debut', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'fin', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'nbj', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'nbh', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'creation', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'commercial', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'encaissement', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'payeur', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'commission', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'partenaire', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'facture', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'statutPaiementCommission', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'tauxCommission'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'ref', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'salle', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'signature', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'fixe', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'recu', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'tva', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'accord', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'debut', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'fin', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'nbj', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'nbh', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'creation', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'commercial', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'encaissement', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'payeur', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'commission', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'partenaire', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'facture', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'commentaires', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'statutPaiementCommission', '' . "\0" . 'App\\Entity\\Domiciliation' . "\0" . 'tauxCommission'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Domiciliation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRef', []);

        return parent::getRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setRef($ref)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRef', [$ref]);

        return parent::setRef($ref);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalle', []);

        return parent::getSalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalle($salle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalle', [$salle]);

        return parent::setSalle($salle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', []);

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu($lieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', [$lieu]);

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignature', []);

        return parent::getSignature();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignature($signature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignature', [$signature]);

        return parent::setSignature($signature);
    }

    /**
     * {@inheritDoc}
     */
    public function getFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFixe', []);

        return parent::getFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFixe($fixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixe', [$fixe]);

        return parent::setFixe($fixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecu', []);

        return parent::getRecu();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecu($recu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecu', [$recu]);

        return parent::setRecu($recu);
    }

    /**
     * {@inheritDoc}
     */
    public function getTva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTva', []);

        return parent::getTva();
    }

    /**
     * {@inheritDoc}
     */
    public function setTva($tva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTva', [$tva]);

        return parent::setTva($tva);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccord()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccord', []);

        return parent::getAccord();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccord($accord)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccord', [$accord]);

        return parent::setAccord($accord);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebut', []);

        return parent::getDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebut($debut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebut', [$debut]);

        return parent::setDebut($debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFin', []);

        return parent::getFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFin($fin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFin', [$fin]);

        return parent::setFin($fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbj', []);

        return parent::getNbj();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbj($nbj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbj', [$nbj]);

        return parent::setNbj($nbj);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbh', []);

        return parent::getNbh();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbh($nbh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbh', [$nbh]);

        return parent::setNbh($nbh);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreation', []);

        return parent::getCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreation($creation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreation', [$creation]);

        return parent::setCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommercial', []);

        return parent::getCommercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommercial($commercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommercial', [$commercial]);

        return parent::setCommercial($commercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncaissement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncaissement', []);

        return parent::getEncaissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncaissement($encaissement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncaissement', [$encaissement]);

        return parent::setEncaissement($encaissement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeur', []);

        return parent::getPayeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeur($payeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeur', [$payeur]);

        return parent::setPayeur($payeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommission', []);

        return parent::getCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommission($commission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommission', [$commission]);

        return parent::setCommission($commission);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartenaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartenaire', []);

        return parent::getPartenaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartenaire($partenaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartenaire', [$partenaire]);

        return parent::setPartenaire($partenaire);
    }

    /**
     * {@inheritDoc}
     */
    public function setFacture(?\App\Entity\FactureDomiciliation $facture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacture', [$facture]);

        return parent::setFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacture', []);

        return parent::getFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaires($commentaires): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaires', [$commentaires]);

        parent::setCommentaires($commentaires);
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaires(\App\Entity\DomiciliationNote $commentaire): \App\Entity\Domiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaires', [$commentaire]);

        return parent::addCommentaires($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function getTablename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTablename', []);

        return parent::getTablename();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutPaiementCommission(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutPaiementCommission', []);

        return parent::getStatutPaiementCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutPaiementCommission(?int $statutPaiementCommission): \App\Entity\Domiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutPaiementCommission', [$statutPaiementCommission]);

        return parent::setStatutPaiementCommission($statutPaiementCommission);
    }

    /**
     * {@inheritDoc}
     */
    public function getTauxCommission(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTauxCommission', []);

        return parent::getTauxCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setTauxCommission(?int $tauxCommission): \App\Entity\Domiciliation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTauxCommission', [$tauxCommission]);

        return parent::setTauxCommission($tauxCommission);
    }

}
