<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VT1Rk0q' shared service.

return $this->privates['.service_locator.VT1Rk0q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'menuRepository' => ['privates', 'App\\Repository\\MenuRepository', 'getMenuRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'utilisateurManager' => ['privates', 'App\\Manager\\UtilisateurManager', 'getUtilisateurManagerService', false],
    'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
], [
    'menuRepository' => 'App\\Repository\\MenuRepository',
    'paginator' => '?',
    'utilisateurManager' => 'App\\Manager\\UtilisateurManager',
    'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
]);
