<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.R6Spvsq' shared service.

return $this->privates['.service_locator.R6Spvsq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contactManager' => ['privates', 'App\\Manager\\ContactManager', 'getContactManagerService.php', true],
    'dossier' => ['privates', '.errored..service_locator.R6Spvsq.App\\Entity\\FormationDossier', NULL, 'Cannot autowire service ".service_locator.R6Spvsq": it references class "App\\Entity\\FormationDossier" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'formationDossierDateManager' => ['privates', 'App\\Manager\\FormationDossierDateManager', 'getFormationDossierDateManagerService.php', true],
    'formationDossierDateRepository' => ['privates', 'App\\Repository\\FormationDossierDateRepository', 'getFormationDossierDateRepositoryService.php', true],
    'manager' => ['privates', 'App\\Manager\\FormationDossierManager', 'getFormationDossierManagerService.php', true],
    'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService.php', true],
], [
    'contactManager' => 'App\\Manager\\ContactManager',
    'dossier' => 'App\\Entity\\FormationDossier',
    'em' => '?',
    'formationDossierDateManager' => 'App\\Manager\\FormationDossierDateManager',
    'formationDossierDateRepository' => 'App\\Repository\\FormationDossierDateRepository',
    'manager' => 'App\\Manager\\FormationDossierManager',
    'villeRepository' => 'App\\Repository\\VilleRepository',
]);
