<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Rv60dUz' shared service.

return $this->privates['.service_locator.Rv60dUz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'lead' => ['privates', '.errored..service_locator.Rv60dUz.App\\Entity\\Lead', NULL, 'Cannot autowire service ".service_locator.Rv60dUz": it references class "App\\Entity\\Lead" but no such service exists.'],
], [
    'lead' => 'App\\Entity\\Lead',
]);
