<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0dF5ZI1' shared service.

return $this->privates['.service_locator.0dF5ZI1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'propal' => ['privates', '.errored..service_locator.0dF5ZI1.App\\Entity\\Propal', NULL, 'Cannot autowire service ".service_locator.0dF5ZI1": it references class "App\\Entity\\Propal" but no such service exists.'],
], [
    'propal' => 'App\\Entity\\Propal',
]);
