<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.u4U6TNf' shared service.

return $this->privates['.service_locator.u4U6TNf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'formationDossierManager' => ['privates', 'App\\Manager\\FormationDossierManager', 'getFormationDossierManagerService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
    'statutRepository' => ['privates', 'App\\Repository\\CommissionStatutRepository', 'getCommissionStatutRepositoryService.php', true],
], [
    'formationDossierManager' => 'App\\Manager\\FormationDossierManager',
    'paginator' => '?',
    'statutRepository' => 'App\\Repository\\CommissionStatutRepository',
]);
