<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.osKIGk8' shared service.

return $this->privates['.service_locator.osKIGk8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'avoirManager' => ['privates', 'App\\Manager\\AvoirManager', 'getAvoirManagerService.php', true],
], [
    'avoirManager' => 'App\\Manager\\AvoirManager',
]);
