<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.knkWwz2' shared service.

return $this->privates['.service_locator.knkWwz2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'factureRepository' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService.php', true],
], [
    'factureRepository' => 'App\\Repository\\FactureRepository',
]);
