<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NVY4hoW' shared service.

return $this->privates['.service_locator.NVY4hoW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'avoir' => ['privates', '.errored..service_locator.NVY4hoW.App\\Entity\\Avoir', NULL, 'Cannot autowire service ".service_locator.NVY4hoW": it references class "App\\Entity\\Avoir" but no such service exists.'],
    'factureRepo' => ['privates', 'App\\Repository\\FactureRepository', 'getFactureRepositoryService.php', true],
    'facturemanager' => ['privates', 'App\\Manager\\FactureManager', 'getFactureManagerService.php', true],
    'formationDossierDateRepository' => ['privates', 'App\\Repository\\FormationDossierDateRepository', 'getFormationDossierDateRepositoryService.php', true],
], [
    'avoir' => 'App\\Entity\\Avoir',
    'factureRepo' => 'App\\Repository\\FactureRepository',
    'facturemanager' => 'App\\Manager\\FactureManager',
    'formationDossierDateRepository' => 'App\\Repository\\FormationDossierDateRepository',
]);
