<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DItvEXA' shared service.

return $this->privates['.service_locator.DItvEXA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contactRepo' => ['privates', 'App\\Repository\\ContactRepository', 'getContactRepositoryService.php', true],
    'facture' => ['privates', '.errored..service_locator.DItvEXA.App\\Entity\\Facture', NULL, 'Cannot autowire service ".service_locator.DItvEXA": it references class "App\\Entity\\Facture" but no such service exists.'],
    'factureManager' => ['privates', 'App\\Manager\\FactureManager', 'getFactureManagerService.php', true],
    'formationDossierDateRepo' => ['privates', 'App\\Repository\\FormationDossierDateRepository', 'getFormationDossierDateRepositoryService.php', true],
    'formationDossierRepo' => ['privates', 'App\\Repository\\FormationDossierRepository', 'getFormationDossierRepositoryService.php', true],
], [
    'contactRepo' => 'App\\Repository\\ContactRepository',
    'facture' => 'App\\Entity\\Facture',
    'factureManager' => 'App\\Manager\\FactureManager',
    'formationDossierDateRepo' => 'App\\Repository\\FormationDossierDateRepository',
    'formationDossierRepo' => 'App\\Repository\\FormationDossierRepository',
]);
