<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MzY4pe0' shared service.

return $this->privates['.service_locator.MzY4pe0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'contactRepository' => ['privates', 'App\\Repository\\ContactRepository', 'getContactRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
], [
    'contactRepository' => 'App\\Repository\\ContactRepository',
    'paginator' => '?',
]);
