<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\Voter\CrmVoter' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
include_once $this->targetDirs[3].'/src/Security/Voter/CrmVoter.php';

return $this->privates['App\\Security\\Voter\\CrmVoter'] = new \App\Security\Voter\CrmVoter(($this->privates['App\\Repository\\MenuRepository'] ?? $this->load('getMenuRepositoryService.php')));
