<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CatalogueController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/BaseController.php';
include_once $this->targetDirs[3].'/src/Controller/CatalogueController.php';

$this->services['App\\Controller\\CatalogueController'] = $instance = new \App\Controller\CatalogueController(($this->privates['security.helper'] ?? $this->getSecurity_HelperService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['App\\Repository\\FormationCatalogueRepository'] ?? $this->load('getFormationCatalogueRepositoryService.php')), ($this->services['knp_paginator'] ?? $this->load('getKnpPaginatorService.php')));

$instance->setContainer(($this->privates['.service_locator.E18xQID'] ?? $this->load('get_ServiceLocator_E18xQIDService.php'))->withContext('App\\Controller\\CatalogueController', $this));

return $instance;
