<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Form\\AdresseType' => ['privates', 'App\\Form\\AdresseType', 'getAdresseTypeService.php', true],
    'App\\Form\\AvoirFactType' => ['privates', 'App\\Form\\AvoirFactType', 'getAvoirFactTypeService.php', true],
    'App\\Form\\AvoirType' => ['privates', 'App\\Form\\AvoirType', 'getAvoirTypeService.php', true],
    'App\\Form\\CiviliteType' => ['privates', 'App\\Form\\CiviliteType', 'getCiviliteTypeService.php', true],
    'App\\Form\\CommentaireType' => ['privates', 'App\\Form\\CommentaireType', 'getCommentaireTypeService.php', true],
    'App\\Form\\Competence1Type' => ['privates', 'App\\Form\\Competence1Type', 'getCompetence1TypeService.php', true],
    'App\\Form\\CompetenceType' => ['privates', 'App\\Form\\CompetenceType', 'getCompetenceTypeService.php', true],
    'App\\Form\\ContactCustomType' => ['privates', 'App\\Form\\ContactCustomType', 'getContactCustomTypeService.php', true],
    'App\\Form\\ContactFilterType' => ['privates', 'App\\Form\\ContactFilterType', 'getContactFilterTypeService.php', true],
    'App\\Form\\ContactType' => ['privates', 'App\\Form\\ContactType', 'getContactTypeService.php', true],
    'App\\Form\\ContactTypeType' => ['privates', 'App\\Form\\ContactTypeType', 'getContactTypeTypeService.php', true],
    'App\\Form\\DomiciliationType' => ['privates', 'App\\Form\\DomiciliationType', 'getDomiciliationTypeService.php', true],
    'App\\Form\\DossierType' => ['privates', 'App\\Form\\DossierType', 'getDossierTypeService.php', true],
    'App\\Form\\EditDomByFactType' => ['privates', 'App\\Form\\EditDomByFactType', 'getEditDomByFactTypeService.php', true],
    'App\\Form\\EditFactureDomType' => ['privates', 'App\\Form\\EditFactureDomType', 'getEditFactureDomTypeService.php', true],
    'App\\Form\\EditStatusType' => ['privates', 'App\\Form\\EditStatusType', 'getEditStatusTypeService.php', true],
    'App\\Form\\EncaissementFilterType' => ['privates', 'App\\Form\\EncaissementFilterType', 'getEncaissementFilterTypeService.php', true],
    'App\\Form\\EncaissementType' => ['privates', 'App\\Form\\EncaissementType', 'getEncaissementTypeService.php', true],
    'App\\Form\\FacturationType' => ['privates', 'App\\Form\\FacturationType', 'getFacturationTypeService.php', true],
    'App\\Form\\FactureAvoirType' => ['privates', 'App\\Form\\FactureAvoirType', 'getFactureAvoirTypeService.php', true],
    'App\\Form\\FactureDomiciliationType' => ['privates', 'App\\Form\\FactureDomiciliationType', 'getFactureDomiciliationTypeService.php', true],
    'App\\Form\\FactureFilterType' => ['privates', 'App\\Form\\FactureFilterType', 'getFactureFilterTypeService.php', true],
    'App\\Form\\Filter\\CommissionFilterType' => ['privates', 'App\\Form\\Filter\\CommissionFilterType', 'getCommissionFilterTypeService.php', true],
    'App\\Form\\Filter\\CompetenceFilterType' => ['privates', 'App\\Form\\Filter\\CompetenceFilterType', 'getCompetenceFilterTypeService.php', true],
    'App\\Form\\Filter\\DomiciliationFilterType' => ['privates', 'App\\Form\\Filter\\DomiciliationFilterType', 'getDomiciliationFilterTypeService.php', true],
    'App\\Form\\Filter\\FactureDomiciliationFilterType' => ['privates', 'App\\Form\\Filter\\FactureDomiciliationFilterType', 'getFactureDomiciliationFilterTypeService.php', true],
    'App\\Form\\Filter\\FactureFormationFilterType' => ['privates', 'App\\Form\\Filter\\FactureFormationFilterType', 'getFactureFormationFilterTypeService.php', true],
    'App\\Form\\Filter\\FormationCatalogueFilterType' => ['privates', 'App\\Form\\Filter\\FormationCatalogueFilterType', 'getFormationCatalogueFilterTypeService.php', true],
    'App\\Form\\Filter\\FormationFilterType' => ['privates', 'App\\Form\\Filter\\FormationFilterType', 'getFormationFilterTypeService.php', true],
    'App\\Form\\Filter\\LeadFilterType' => ['privates', 'App\\Form\\Filter\\LeadFilterType', 'getLeadFilterTypeService.php', true],
    'App\\Form\\Filter\\LogFilterType' => ['privates', 'App\\Form\\Filter\\LogFilterType', 'getLogFilterTypeService.php', true],
    'App\\Form\\Filter\\PropalFilterType' => ['privates', 'App\\Form\\Filter\\PropalFilterType', 'getPropalFilterTypeService.php', true],
    'App\\Form\\FormateurCommentdispType' => ['privates', 'App\\Form\\FormateurCommentdispType', 'getFormateurCommentdispTypeService.php', true],
    'App\\Form\\FormateurFilterType' => ['privates', 'App\\Form\\FormateurFilterType', 'getFormateurFilterTypeService.php', true],
    'App\\Form\\FormateurType' => ['privates', 'App\\Form\\FormateurType', 'getFormateurTypeService.php', true],
    'App\\Form\\FormationCatalogueType' => ['privates', 'App\\Form\\FormationCatalogueType', 'getFormationCatalogueTypeService.php', true],
    'App\\Form\\FormationDossierFilterType' => ['privates', 'App\\Form\\FormationDossierFilterType', 'getFormationDossierFilterTypeService.php', true],
    'App\\Form\\FormationType' => ['privates', 'App\\Form\\FormationType', 'getFormationTypeService.php', true],
    'App\\Form\\LeadType' => ['privates', 'App\\Form\\LeadType', 'getLeadTypeService.php', true],
    'App\\Form\\MailType' => ['privates', 'App\\Form\\MailType', 'getMailTypeService.php', true],
    'App\\Form\\NoteFilterType' => ['privates', 'App\\Form\\NoteFilterType', 'getNoteFilterTypeService.php', true],
    'App\\Form\\NoteType' => ['privates', 'App\\Form\\NoteType', 'getNoteTypeService.php', true],
    'App\\Form\\OpcaFilterType' => ['privates', 'App\\Form\\OpcaFilterType', 'getOpcaFilterTypeService.php', true],
    'App\\Form\\OpcaType' => ['privates', 'App\\Form\\OpcaType', 'getOpcaTypeService.php', true],
    'App\\Form\\PropalType' => ['privates', 'App\\Form\\PropalType', 'getPropalTypeService.php', true],
    'App\\Form\\QualiteType' => ['privates', 'App\\Form\\QualiteType', 'getQualiteTypeService.php', true],
    'App\\Form\\SecteurActiviteType' => ['privates', 'App\\Form\\SecteurActiviteType', 'getSecteurActiviteTypeService.php', true],
    'App\\Form\\SocieteLieeType' => ['privates', 'App\\Form\\SocieteLieeType', 'getSocieteLieeTypeService.php', true],
    'App\\Form\\StagiaireType' => ['privates', 'App\\Form\\StagiaireType', 'getStagiaireTypeService.php', true],
    'App\\Form\\SuiviMissionType' => ['privates', 'App\\Form\\SuiviMissionType', 'getSuiviMissionTypeService.php', true],
    'App\\Form\\TelephoneType' => ['privates', 'App\\Form\\TelephoneType', 'getTelephoneTypeService.php', true],
    'App\\Form\\Type\\CrmDateType' => ['privates', 'App\\Form\\Type\\CrmDateType', 'getCrmDateTypeService.php', true],
    'App\\Form\\Type\\CrmMoneyType' => ['privates', 'App\\Form\\Type\\CrmMoneyType', 'getCrmMoneyTypeService.php', true],
    'App\\Form\\Type\\DateNowType' => ['privates', 'App\\Form\\Type\\DateNowType', 'getDateNowTypeService.php', true],
    'App\\Form\\Type\\EntityToTextType' => ['privates', 'App\\Form\\Type\\EntityToTextType', 'getEntityToTextTypeService.php', true],
    'App\\Form\\Type\\StructureType' => ['privates', 'App\\Form\\Type\\StructureType', 'getStructureTypeService.php', true],
    'App\\Form\\UrlType' => ['privates', 'App\\Form\\UrlType', 'getUrlTypeService.php', true],
    'App\\Form\\UtilisateurFilterType' => ['privates', 'App\\Form\\UtilisateurFilterType', 'getUtilisateurFilterTypeService.php', true],
    'App\\Form\\UtilisateurType' => ['privates', 'App\\Form\\UtilisateurType', 'getUtilisateurTypeService.php', true],
    'App\\Form\\VilleType' => ['privates', 'App\\Form\\VilleType', 'getVilleTypeService.php', true],
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', 'form.type.file', 'getForm_Type_FileService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
], [
    'App\\Form\\AdresseType' => '?',
    'App\\Form\\AvoirFactType' => '?',
    'App\\Form\\AvoirType' => '?',
    'App\\Form\\CiviliteType' => '?',
    'App\\Form\\CommentaireType' => '?',
    'App\\Form\\Competence1Type' => '?',
    'App\\Form\\CompetenceType' => '?',
    'App\\Form\\ContactCustomType' => '?',
    'App\\Form\\ContactFilterType' => '?',
    'App\\Form\\ContactType' => '?',
    'App\\Form\\ContactTypeType' => '?',
    'App\\Form\\DomiciliationType' => '?',
    'App\\Form\\DossierType' => '?',
    'App\\Form\\EditDomByFactType' => '?',
    'App\\Form\\EditFactureDomType' => '?',
    'App\\Form\\EditStatusType' => '?',
    'App\\Form\\EncaissementFilterType' => '?',
    'App\\Form\\EncaissementType' => '?',
    'App\\Form\\FacturationType' => '?',
    'App\\Form\\FactureAvoirType' => '?',
    'App\\Form\\FactureDomiciliationType' => '?',
    'App\\Form\\FactureFilterType' => '?',
    'App\\Form\\Filter\\CommissionFilterType' => '?',
    'App\\Form\\Filter\\CompetenceFilterType' => '?',
    'App\\Form\\Filter\\DomiciliationFilterType' => '?',
    'App\\Form\\Filter\\FactureDomiciliationFilterType' => '?',
    'App\\Form\\Filter\\FactureFormationFilterType' => '?',
    'App\\Form\\Filter\\FormationCatalogueFilterType' => '?',
    'App\\Form\\Filter\\FormationFilterType' => '?',
    'App\\Form\\Filter\\LeadFilterType' => '?',
    'App\\Form\\Filter\\LogFilterType' => '?',
    'App\\Form\\Filter\\PropalFilterType' => '?',
    'App\\Form\\FormateurCommentdispType' => '?',
    'App\\Form\\FormateurFilterType' => '?',
    'App\\Form\\FormateurType' => '?',
    'App\\Form\\FormationCatalogueType' => '?',
    'App\\Form\\FormationDossierFilterType' => '?',
    'App\\Form\\FormationType' => '?',
    'App\\Form\\LeadType' => '?',
    'App\\Form\\MailType' => '?',
    'App\\Form\\NoteFilterType' => '?',
    'App\\Form\\NoteType' => '?',
    'App\\Form\\OpcaFilterType' => '?',
    'App\\Form\\OpcaType' => '?',
    'App\\Form\\PropalType' => '?',
    'App\\Form\\QualiteType' => '?',
    'App\\Form\\SecteurActiviteType' => '?',
    'App\\Form\\SocieteLieeType' => '?',
    'App\\Form\\StagiaireType' => '?',
    'App\\Form\\SuiviMissionType' => '?',
    'App\\Form\\TelephoneType' => '?',
    'App\\Form\\Type\\CrmDateType' => '?',
    'App\\Form\\Type\\CrmMoneyType' => '?',
    'App\\Form\\Type\\DateNowType' => '?',
    'App\\Form\\Type\\EntityToTextType' => '?',
    'App\\Form\\Type\\StructureType' => '?',
    'App\\Form\\UrlType' => '?',
    'App\\Form\\UtilisateurFilterType' => '?',
    'App\\Form\\UtilisateurType' => '?',
    'App\\Form\\VilleType' => '?',
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.transformation_failure_handling'] ?? $this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
}, 5), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? ($this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? ($this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
