<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\FactureAvoirType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/FactureAvoirType.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/DataTransformerInterface.php';
include_once $this->targetDirs[3].'/src/Form/DataTransformer/OpcaObjectTransformer.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return $this->privates['App\\Form\\FactureAvoirType'] = new \App\Form\FactureAvoirType($a, ($this->privates['App\\Repository\\FactureStatutRepository'] ?? $this->load('getFactureStatutRepositoryService.php')), ($this->privates['App\\Repository\\ContactRepository'] ?? $this->load('getContactRepositoryService.php')), ($this->privates['App\\Repository\\FactureRepository'] ?? $this->load('getFactureRepositoryService.php')), ($this->privates['App\\Repository\\StructureRepository'] ?? $this->load('getStructureRepositoryService.php')), ($this->privates['App\\Repository\\AvoirRepository'] ?? $this->load('getAvoirRepositoryService.php')), ($this->privates['App\\Form\\DataTransformer\\SocieteObjectTransformer'] ?? $this->load('getSocieteObjectTransformerService.php')), new \App\Form\DataTransformer\OpcaObjectTransformer($a));
