<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\SocieteLieeType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/SocieteLieeType.php';

return $this->privates['App\\Form\\SocieteLieeType'] = new \App\Form\SocieteLieeType(($this->privates['App\\Form\\DataTransformer\\SocieteTransformer'] ?? $this->load('getSocieteTransformerService.php')));
