<?php
/**
 * file CrmDateType.php
 */

namespace App\Form\Type;

use App\Form\DataTransformer\DateTimeTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CrmDateType extends AbstractType
{
    private $dateTimeTransformer;

    public function __construct(DateTimeTransformer $dateTimeTransformer) {
        $dateTimeTransformer->setFormat('d/m/Y');
        $dateTimeTransformer->setNullable(true);
        $this->dateTimeTransformer = $dateTimeTransformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options) {
        parent::buildForm($builder, $options);
        $builder->addModelTransformer($this->dateTimeTransformer);
        $builder->resetViewTransformers();
    }

    public function getParent() {
        return DateType::class;
    }

    public function configureOptions(OptionsResolver $resolver) {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'widget'        => 'single_text',
            'html5'         => false,
            'attr'          => ['class' => 'js-datepicker text-center', 'autocomplete' => 'off'],
            'format' => 'd/m/Y',
            'empty_data' => ''
        ]);
    }
}