name: phpDocumentor

on:
  push:
    branches: [ master ]

jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run phpdoc
        run: |
          cd app
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3

      - name: git commit
        run: |
          mv app/docs/* docs
          git config user.name "GitHub Actions"
          git config user.email ""
          git add .
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git push
