name: PHP Linting
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: overtrue/phplint@8.0
          with:
            path: ./app/
            options: --exclude=vendor --exclude=var
