<?php
/**
 * Created by PhpStorm.
 * User: anthony
 * Date: 05/12/2019
 * Time: 17:36
 */

namespace App\Repository;

use App\Entity\Structure;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * Class StructureRepository
 * @package App\Repository
 *
 */
class StructureRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Structure::class);
    }

    /**
     *
     */
    public function getQueryListStructure() {
        $qb = $this->createQueryBuilder('s');

        return $qb
                ->andWhere('s.deletedAt = :false')
                ->setParameter(':false', false)
                ->orderBy('s.structure', 'ASC')
            ;
    }

    /**
     * override symfony default method to add criteria
     *
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null) {
        $criteria = array_merge(['deletedAt' => false], $criteria);
        return parent::findBy($criteria, $orderBy, $limit, $offset); // TODO: Change the autogenerated stub
    }
}